name: build

on:
  push:
    branches:
      - main
      - master
  pull_request:
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]

    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.3
          with:
            submodules: recursive
            fetch-depth: 2
            
        - name: Run setup script
          run: .\setup.bat

        - name: Run build script
          run: .\build.bat
